// ============================================================
// Panini FIFA World Cup 2026 – Player Names Database
// Format: PLAYER_NAMES[countryCode][0] = Sticker #1 (Badge/Logo)
//         PLAYER_NAMES[countryCode][1] = Sticker #2 (Spieler 1)
//         ...
//         PLAYER_NAMES[countryCode][19] = Sticker #20 (Spieler 19)
// ============================================================

export const PLAYER_NAMES: Record<string, string[]> = {
  FWC: [
    "Offizielles Emblem",
    "Offizielles Emblem",
    "Offizielle Maskottchen",
    "Offizieller Slogan",
    "Offizieller Ball",
    "Kanada – Gastgeber",
    "Mexiko – Gastgeber",
    "USA – Gastgeber",
    "Italien 1934",
    "Uruguay 1950",
    "Deutschland 1954",
    "Brasilien 1962",
    "Deutschland 1974",
    "Argentinien 1986",
    "Brasilien 1994",
    "Brasilien 2002",
    "Italien 2006",
    "Deutschland 2014",
    "Argentinien 2022",
  ],
  MEX: [
    "Team-Logo",
    "Luis Malagón",
    "Johan Vasquez",
    "Jorge Sánchez",
    "Cesar Montes",
    "Jesus Gallardo",
    "Israel Reyes",
    "Diego Lainez",
    "Carlos Rodriguez",
    "Edson Alvarez",
    "Orbelin Pineda",
    "Marcel Ruiz",
    "Team-Foto",
    "Érick Sánchez",
    "Hirving Lozano",
    "Santiago Giménez",
    "Raúl Jiménez",
    "Alexis Vega",
    "Roberto Alvarado",
    "Cesar Huerta",
  ],
  RSA: [
    "Team-Logo",
    "Ronwen Williams",
    "Sipho Chaine",
    "Aubrey Modiba",
    "Samukele Kabini",
    "Mbekezeli Mbokazi",
    "Khulumani Ndamane",
    "Siyabonga Ngezana",
    "Khuliso Mudau",
    "Nkosinathi Sibisi",
    "Teboho Mokoena",
    "Thalente Mbatha",
    "Team-Foto",
    "Bathasi Aubaas",
    "Yaya Sithole",
    "Sipho Mbule",
    "Lyle Foster",
    "Iqraam Rayners",
    "Mohau Nkota",
    "Oswin Appollis",
  ],
  KOR: [
    "Team-Logo",
    "Hyeon-woo Jo",
    "Seung-Gyu Kim",
    "Min-jae Kim",
    "Yu-min Cho",
    "Young-woo Seol",
    "Han-beom Lee",
    "Tae-seok Lee",
    "Myung-jae Lee",
    "Jae-sung Lee",
    "In-beom Hwang",
    "Kang-in Lee",
    "Team-Foto",
    "Seung-ho Paik",
    "Jens Castrop",
    "Dongg-yeong Lee",
    "Gue-sung Cho",
    "Heung-min Son",
    "Hee-chan Hwang",
    "Hyeon-Gyu Oh",
  ],
  CZE: [
    "Team-Logo",
    "Matej Kovar",
    "Jindrich Stanek",
    "Ladislav Krejci",
    "Vladimir Coufal",
    "Jaroslav Zeleny",
    "Tomas Holes",
    "David Zima",
    "Michal Sadilek",
    "Lukas Provod",
    "Lukas Cerv",
    "Tomas Soucek",
    "Team-Foto",
    "Pavel Sulc",
    "Matej Vydra",
    "Vasil Kusej",
    "Tomas Chory",
    "Vaclav Cerny",
    "Adam Hlozek",
    "Patrik Schick",
  ],
  CAN: [
    "Team-Logo",
    "Dayne St.Clair",
    "Alphonso Davies",
    "Alistair Johnston",
    "Samuel Adekugbe",
    "Riche Larvea",
    "Derek Cornelius",
    "Moïse Bombito",
    "Kamal Miller",
    "Stephen Eustáquio",
    "Ismaël Koné",
    "Jonathan Osorio",
    "Team-Foto",
    "Jacob Shaffelburg",
    "Mathieu Choinière",
    "Niko Sigur",
    "Tajon Buchanan",
    "Liam Millar",
    "Cyle Larin",
    "Jonathan David",
  ],
  BIH: [
    "Team-Logo",
    "Nikola Vasilj",
    "Amer Dedic",
    "Sead Kolasinac",
    "Tarik Muharemovic",
    "Nihad Mujakic",
    "Nikola Katic",
    "Amir Hadziahmetovic",
    "Benjamin Tahirovic",
    "Armin Gigovic",
    "Ivan Sunjic",
    "Ivan Basic",
    "Team-Foto",
    "Dzenis Burnic",
    "Esmir Bajraktarevic",
    "Amar Memic",
    "Ermedin Demirovic",
    "Edin Dzeko",
    "Samed Bazdar",
    "Haris Tabakovic",
  ],
  QAT: [
    "Team-Logo",
    "Meshaal Barsham",
    "Sultan Albrake",
    "Lucas Mendes",
    "Homam Ahmed",
    "Boualem Khoukhi",
    "Pedro Miguel",
    "Tarek Salman",
    "Mohamed Al-Mannai",
    "Karim Boudiaf",
    "Assim Madibo",
    "Ahmed Fatehi",
    "Team-Foto",
    "Mohammed Waad",
    "Abdulaziz Hatem",
    "Hassan Al-Haydos",
    "Edmilson Junior",
    "Akram Hassan Afif",
    "Ahmed Al Ganehi",
    "Almoez Ali",
  ],
  SUI: [
    "Team-Logo",
    "Gregor Kobel",
    "Yvon Mvogo",
    "Manuel Akanji",
    "Ricardo Rodriguez",
    "Nico Elvedi",
    "Aurèle Amenda",
    "Silvan Widmer",
    "Granit Xhaka",
    "Denis Zakaria",
    "Remo Freuler",
    "Fabian Rieder",
    "Team-Foto",
    "Ardon Jashari",
    "Johan Manzambi",
    "Michel Aebischer",
    "Breel Embolo",
    "Ruben Vargas",
    "Dan Ndoye",
    "Zeki Amdouni",
  ],
  BRA: [
    "Team-Logo",
    "Alisson",
    "Bento",
    "Marquinhos",
    "Éder Militão",
    "Gabriel Magalhães",
    "Danilo",
    "Wesley",
    "Lucas Paquetá",
    "Casemiro",
    "Bruno Guimarães",
    "Luiz Henrique",
    "Team-Foto",
    "Vinicius Júnior",
    "Rodrygo",
    "João Pedro",
    "Matheus Cunha",
    "Gabriel Martinelli",
    "Raphinha",
    "Estévão",
  ],
  MAR: [
    "Team-Logo",
    "Yassine Bounou",
    "Munir El Kajoui",
    "Achraf Hakimi",
    "Noussair Mazraoui",
    "Nayef Aguerd",
    "Roman Saiss",
    "Jawad El Yamio",
    "Adam Masina",
    "Sofyan Amrabat",
    "Azzedine Ounahi",
    "Eliesse Ben Seghir",
    "Team-Foto",
    "Bilal El Khannouss",
    "Ismael Saibari",
    "Youssef En-Nesyri",
    "Abde Ezzalzouli",
    "Soufiane Rahimi",
    "Brahim Diaz",
    "Ayoub El Kaabi",
  ],
  HAI: [
    "Team-Logo",
    "Johny Placide",
    "Carlens Arcus",
    "Martin Expérience",
    "Jean-Kevin Duverne",
    "Ricardo Adé",
    "Duke Lacroix",
    "Garven Metusala",
    "Hannes Delcroix",
    "Leverton Pierre",
    "Danley Jean Jacques",
    "Jean-Ricner Bellegarde",
    "Team-Foto",
    "Christopher Attys",
    "Derrick Etienne Jr",
    "Josue Casimir",
    "Ruben Providence",
    "Duckens Nazon",
    "Louicius Deedson",
    "Frantzdy Pierrot",
  ],
  SCO: [
    "Team-Logo",
    "Angus Gunn",
    "Jack Hendry",
    "Kieran Tierney",
    "Aaron Hickey",
    "Andrew Robertson",
    "Scott McKenna",
    "John Souttar",
    "Anthony Ralston",
    "Grant Hanley",
    "Scott McTominay",
    "Billy Gilmour",
    "Team-Foto",
    "Lewis Ferguson",
    "Ryan Christie",
    "Kenny McLean",
    "John McGinn",
    "Lyndon Dykes",
    "Che Adams",
    "Ben Gannon-Doak",
  ],
  USA: [
    "Team-Logo",
    "Math Freese",
    "Chris Richards",
    "Tim Ream",
    "Mark McKenzie",
    "Alex Freeman",
    "Antonee Robinson",
    "Tyler Adams",
    "Tanner Tessmann",
    "Weston McKenny",
    "Christian Roldan",
    "Timothy Weah",
    "Team-Foto",
    "Diego Luna",
    "Malik Tillman",
    "Christian Pulisic",
    "Brenden Aaronson",
    "Ricardo Pepi",
    "Haji Wright",
    "Folarin Balogun",
  ],
  PAR: [
    "Team-Logo",
    "Roberto Fernandez",
    "Orlando Gill",
    "Gustavo Gomez",
    "Fabián Balbuena",
    "Juan José Cáceres",
    "Omar Alderete",
    "Junior Alonso",
    "Mathías Villasanti",
    "Diego Gomez",
    "Damián Bobadilla",
    "Andres Cubas",
    "Team-Foto",
    "Matias Galarza Fonda",
    "Julio Enciso",
    "Alejandro Romero Gamarra",
    "Miguel Almirón",
    "Ramon Sosa",
    "Angel Romero",
    "Antonio Sanabria",
  ],
  AUS: [
    "Team-Logo",
    "Mathew Ryan",
    "Joe Gauci",
    "Harry Souttar",
    "Alessandro Circati",
    "Jordan Bos",
    "Aziz Behich",
    "Cameron Burgess",
    "Lewis Miller",
    "Milos Degenek",
    "Jackson Irvine",
    "Riley McGree",
    "Team-Foto",
    "Aiden O'Neill",
    "Connor Metcalfe",
    "Patrick Yazbek",
    "Craig Goodwin",
    "Kusini Vengi",
    "Nestory Irankunda",
    "Mohamed Touré",
  ],
  TUR: [
    "Team-Logo",
    "Ugurcan Cakir",
    "Mert Muldur",
    "Zeki Celik",
    "Abdulkerim Bardakci",
    "Caglar Soyuncu",
    "Merih Demiral",
    "Ferdi Kadioglu",
    "Kaan Ayhan",
    "Ismail Yuksek",
    "Hakan Calhanoglu",
    "Orkun Kokcu",
    "Team-Foto",
    "Arda Guler",
    "Irfan Can Kahveci",
    "Yunus Akgun",
    "Can Uzun",
    "Baris Alper Yilmaz",
    "Kerem Akturkoglu",
    "Kenan Yildiz",
  ],
  GER: [
    "Team-Logo",
    "Marc-André ter Stegen",
    "Jonathan Tah",
    "David Raum",
    "Nico Schlotterbeck",
    "Antonio Rüdiger",
    "Waldemar Anton",
    "Ridle Baku",
    "Maximilian Mittelstadt",
    "Joshua Kimmich",
    "Florian Wirtz",
    "Felix Nmecha",
    "Team-Foto",
    "Leon Goretzka",
    "Jamal Musiala",
    "Serge Gnabry",
    "Kai Havertz",
    "Leroy Sane",
    "Karim Adeyemi",
    "Nick Woltemade",
  ],
  CUW: [
    "Team-Logo",
    "Eloy Room",
    "Armando Obispo",
    "Sherel Floranus",
    "Jurien Gaari",
    "Joshua Brenet",
    "Roshon Van Eijma",
    "Shurandy Sambo",
    "Livano Comenencia",
    "Godfried Roemeratoe",
    "Juninho Bacuna",
    "Leandro Bacuna",
    "Team-Foto",
    "Tahith Chong",
    "Kenji Gorre",
    "Jearl Margaritha",
    "Jurgen Locadia",
    "Jeremy Antonisse",
    "Gervane Kastaneer",
    "Sontje Hansen",
  ],
  CIV: [
    "Team-Logo",
    "Yahia Fofana",
    "Ghislain Konan",
    "Wilfried Singo",
    "Odilon Kossounou",
    "Evan Ndicka",
    "Willy Boly",
    "Emmanuel Agbadou",
    "Ousmane Diomande",
    "Franck Kessie",
    "Seko Fofana",
    "Ibrahim Sangare",
    "Team-Foto",
    "Jean-Philippe Gbamin",
    "Amad Diallo",
    "Sébastien Haller",
    "Simon Adingra",
    "Yan Diomande",
    "Evann Guessand",
    "Oumar Diakite",
  ],
  ECU: [
    "Team-Logo",
    "Hernán Galíndez",
    "Gonzalo Valle",
    "Piero Hincapié",
    "Pervis Estupiñán",
    "Willian Pacho",
    "Ángelo Preciado",
    "Joel Ordóñez",
    "Moises Caicedo",
    "Alan Franco",
    "Kendry Paez",
    "Pedro Vite",
    "Team-Foto",
    "John Veboah",
    "Leonardo Campana",
    "Gonzalo Plata",
    "Nilson Angulo",
    "Alan Minda",
    "Kevin Rodriguez",
    "Enner Valencia",
  ],
  NED: [
    "Team-Logo",
    "Bart Verbruggen",
    "Virgil van Dijk",
    "Micky van de Ven",
    "Jurrien Timber",
    "Denzel Dumfries",
    "Nathan Aké",
    "Jeremie Frimpong",
    "Jan Paul van Hecke",
    "Tijjani Reijnders",
    "Ryan Gravenberch",
    "Teun Koopmeiners",
    "Team-Foto",
    "Frenkie de Jong",
    "Xavi Simons",
    "Justin Kluivert",
    "Memphis Depay",
    "Donyell Malen",
    "Wout Weghorst",
    "Cody Gakpo",
  ],
  JPN: [
    "Team-Logo",
    "Zion Suzuki",
    "Henry Heroki Mochizuki",
    "Ayumu Seko",
    "Junnosuke Suzuki",
    "Shogo Taniguchi",
    "Tsuyoshi Watanabe",
    "Kaishu Sano",
    "Yuki Soma",
    "Ao Tanaka",
    "Daichi Kamada",
    "Takefusa Kubo",
    "Team-Foto",
    "Ritsu Doan",
    "Keito Nakamura",
    "Takumi Minamino",
    "Shuto Machino",
    "Junya Ito",
    "Koki Ogawa",
    "Ayase Ueda",
  ],
  SWE: [
    "Team-Logo",
    "Victor Johansson",
    "Isak Hien",
    "Gabriel Gudmundsson",
    "Emil Holm",
    "Victor Nilsson Lindelöf",
    "Gustaf Lagerbielke",
    "Lucas Bergvall",
    "Hugo Larsson",
    "Jesper Karlström",
    "Yasin Ayari",
    "Mattias Svanberg",
    "Team-Foto",
    "Daniel Svensson",
    "Ken Sema",
    "Roony Bardghji",
    "Dejan Kulusevski",
    "Anthony Elanga",
    "Alexander Isak",
    "Viktor Gyökeres",
  ],
  TUN: [
    "Team-Logo",
    "Bechir Ben Said",
    "Aymen Dahmen",
    "Yan Valery",
    "Montassar Talbi",
    "Yassine Meriah",
    "Ali Abdi",
    "Dylan Bronn",
    "Ellyes Skhiri",
    "Aissa Laidouni",
    "Ferjani Sassi",
    "Mohamed Ali Ben Romdhane",
    "Team-Foto",
    "Hannibal Mejbri",
    "Elias Achouri",
    "Elias Saad",
    "Hazem Mastouri",
    "Ismael Gharbi",
    "Sayfallah Ltaief",
    "Naim Sliti",
  ],
  BEL: [
    "Team-Logo",
    "Thibaut Courtois",
    "Arthur Theate",
    "Timothy Castagne",
    "Zeno Debast",
    "Brandon Mechele",
    "Maxim De Cuyper",
    "Thomas Meunier",
    "Youri Tielemans",
    "Amadou Onana",
    "Nicolas Raskin",
    "Alexis Saelemaekers",
    "Team-Foto",
    "Hans Vanaken",
    "Kevin De Bruyne",
    "Jérémy Doku",
    "Charles De Ketelaere",
    "Leandro Trossard",
    "Loïs Openda",
    "Romelu Lukaku",
  ],
  EGY: [
    "Team-Logo",
    "Mohamed El Shenawy",
    "Mohamed Hany",
    "Mohamed Hamdy",
    "Yasser Ibrahim",
    "Khaled Sobhi",
    "Ramy Rabia",
    "Hossam Abdelmaguid",
    "Ahmed Fatouh",
    "Marwan Attia",
    "Zizo",
    "Hamdy Fathy",
    "Team-Foto",
    "Mohamed Lasheen",
    "Emam Ashour",
    "Osama Faisal",
    "Mohamed Salah",
    "Mostafa Mohamed",
    "Trezeguet",
    "Omar Marmoush",
  ],
  IRN: [
    "Team-Logo",
    "Alireza Beiranvand",
    "Morteza Pouraliganji",
    "Ehsan Hajsafi",
    "Milad Mohammadi",
    "Shojae Khalilzadeh",
    "Ramin Rezaeian",
    "Hossein Kanaani",
    "Sadegh Moharrami",
    "Saleh Hardani",
    "Saeed Ezatolahi",
    "Saman Ghoddos",
    "Team-Foto",
    "Omid Noorafkan",
    "Roozbeh Cheshmi",
    "Mohammad Mohebi",
    "Sardar Azmoun",
    "Mehdi Taremi",
    "Alireza Jahanbakhsh",
    "Ali Gholizadeh",
  ],
  NZL: [
    "Team-Logo",
    "Max Crocombe Payne",
    "Alex Paulsen",
    "Michael Boxall",
    "Liberato Cacace",
    "Tim Payne",
    "Tyler Bindon",
    "Francis de Vries",
    "Finn Surman",
    "Joe Bell",
    "Sarpreet Singh",
    "Ryan Thomas",
    "Team-Foto",
    "Matthew Garbett",
    "Marko Stamenić",
    "Ben Old",
    "Chris Wood",
    "Elijah Just",
    "Callum McCowatt",
    "Kosta Barbarouses",
  ],
  ESP: [
    "Team-Logo",
    "Unai Simon",
    "Robin Le Normand",
    "Aymeric Laporte",
    "Dean Huijsen",
    "Pedro Porro",
    "Dani Carvajal",
    "Marc Cucurella",
    "Martín Zubimendi",
    "Rodri",
    "Pedri",
    "Fabian Ruiz",
    "Team-Foto",
    "Mikel Merino",
    "Lamine Yamal",
    "Dani Olmo",
    "Nico Williams",
    "Ferran Torres",
    "Álvaro Morata",
    "Mikel Oyarzabal",
  ],
  CPV: [
    "Team-Logo",
    "Vozinha",
    "Logan Costa",
    "Pico",
    "Diney",
    "Steven Moreira",
    "Wagner Pina",
    "Joao Paulo",
    "Yannick Semedo",
    "Kevin Pina",
    "Patrick Andrade",
    "Jamiro Monteiro",
    "Team-Foto",
    "Deroy Duarte",
    "Garry Rodrigues",
    "Jovane Cabral",
    "Ryan Mendes",
    "Dailon Livramento",
    "Willy Semedo",
    "Bebe",
  ],
  KSA: [
    "Team-Logo",
    "Nawaf Alaqidi",
    "Abdulrahman Al-Sanbi",
    "Saud Abdulhamid",
    "Nawaf Bouwashl",
    "Jihad Thakri",
    "Moteb Al-Harbi",
    "Hassan Altambakti",
    "Musab Aljuwayr",
    "Ziyad Aljohani",
    "Abdullah Alkhaibari",
    "Nasser Aldawsari",
    "Team-Foto",
    "Saleh Abu Alshamat",
    "Marwan Alsahafi",
    "Salem Aldawsari",
    "Abdulrahman Al-Aboud",
    "Feras Akbrikan",
    "Saleh Alshehri",
    "Abdullah Al-Hamdan",
  ],
  URU: [
    "Team-Logo",
    "Sergio Rochet",
    "Santiago Mele",
    "Ronald Araujo",
    "José María Giménez",
    "Sebastian Caceres",
    "Mathias Olivera",
    "Guillermo Varela",
    "Nahitan Nandez",
    "Federico Valverde",
    "Giorgian De Arrascaeta",
    "Rodrigo Bentancur",
    "Team-Foto",
    "Manuel Ugarte",
    "Nicolás de la Cruz",
    "Maxi Araujo",
    "Darwin Núñez",
    "Federico Viñas",
    "Rodrigo Aguirre",
    "Facundo Pellistri",
  ],
  FRA: [
    "Team-Logo",
    "Mike Maignan",
    "Theo Hernandez",
    "William Saliba",
    "Jules Kounde",
    "Ibrahima Konate",
    "Dayot Upamecano",
    "Lucas Digne",
    "Aurélien Tchouaméni",
    "Eduardo Camavinga",
    "Manu Kone",
    "Adrien Rabiot",
    "Team-Foto",
    "Michael Olise",
    "Ousmane Dembele",
    "Bradley Barcola",
    "Désiré Doué",
    "Kingsley Coman",
    "Hugo Ekitike",
    "Kylian Mbappe",
  ],
  SEN: [
    "Team-Logo",
    "Edouard Mendy",
    "Yehvann Diouf",
    "Moussa Niakhaté",
    "Abdoulaye Seck",
    "Ismail Jakobs",
    "El Hadji Malick Diouf",
    "Kalidou Koulibaly",
    "Idrissa Gana Gueye",
    "Pape Matar Sarr",
    "Pape Gueye",
    "Habib Diarra",
    "Team-Foto",
    "Lamine Camara",
    "Sadio Mane",
    "Ismaïla Sarr",
    "Boulaye Dia",
    "Iliman Ndiaye",
    "Nicolas Jackson",
    "Krepin Diatta",
  ],
  IRQ: [
    "Team-Logo",
    "Jalal Hassan",
    "Rebin Sulaka",
    "Hussein Ali",
    "Akam Hashem",
    "Merchas Doski",
    "Zaid Tahseen",
    "Manaf Younis",
    "Zidane Iqbal",
    "Amir Al-Ammari",
    "Ibrahim Bavesh",
    "Ali Jasim",
    "Team-Foto",
    "Youssef Amyn",
    "Aimar Sher",
    "Marko Farji",
    "Osama Rashid",
    "Ali Al-Hamadi",
    "Aymen Hussein",
    "Mohanad Ali",
  ],
  NOR: [
    "Team-Logo",
    "Orjan Nyland",
    "Julian Ryerson",
    "Leo Ostigård",
    "Kristoffer Vassbakk Ajer",
    "Marcus Holmgren Pedersen",
    "David Møller Wolfe",
    "Torbjørn Heggem",
    "Morten Thorsby",
    "Martin Ødegaard",
    "Sander Berge",
    "Andreas Schjelderup",
    "Team-Foto",
    "Patrick Berg",
    "Erling Haaland",
    "Alexander Sørloth",
    "Aron Dønnum",
    "Jorgen Strand Larsen",
    "Antonio Nusa",
    "Oscar Bobb",
  ],
  ARG: [
    "Team-Logo",
    "Emiliano Martinez",
    "Nahuel Molina",
    "Cristian Romero",
    "Nicolas Otamendi",
    "Nicolas Tagliafico",
    "Leonardo Balerdi",
    "Enzo Fernandez",
    "Alexis Mac Allister",
    "Rodrigo De Paul",
    "Exequiel Palacios",
    "Leandro Paredes",
    "Team-Foto",
    "Nico Paz",
    "Franco Mastantuono",
    "Nico Gonzalez",
    "Lionel Messi",
    "Lautaro Martinez",
    "Julian Alvarez",
    "Giuliano Simeone",
  ],
  ALG: [
    "Team-Logo",
    "Alexis Guendouz",
    "Ramy Bensebaini",
    "Youcef Atal",
    "Rayan Aït-Nouri",
    "Mohamed Amine Tougai",
    "Aïssa Mandi",
    "Ismael Bennacer",
    "Houssem Aquar",
    "Hicham Boudaoui",
    "Ramiz Zerrouki",
    "Nabil Bentalab",
    "Team-Foto",
    "Farés Chaibi",
    "Riyad Mahrez",
    "Said Benrahma",
    "Anis Hadj Moussa",
    "Amine Gouiri",
    "Baghdad Bounedjah",
    "Mohammed Amoura",
  ],
  AUT: [
    "Team-Logo",
    "Alexander Schlager",
    "Patrick Pentz",
    "David Alaba",
    "Kevin Danso",
    "Philipp Lienhart",
    "Stefan Posch",
    "Phillipp Mwene",
    "Alexander Prass",
    "Xaver Schlager",
    "Marcel Sabitzer",
    "Konrad Laimer",
    "Team-Foto",
    "Florian Grillitsch",
    "Nicolas Seiwald",
    "Romano Schmid",
    "Patrick Wimmer",
    "Christoph Baumgartner",
    "Michael Gregoritsch",
    "Marko Arnautović",
  ],
  JOR: [
    "Team-Logo",
    "Yazeed Abulaila",
    "Ihsan Haddad",
    "Mohammad Abu Hashish",
    "Yazan Al-Arab",
    "Abdallah Nasib",
    "Saleem Obaid",
    "Mohammad Abualnadi",
    "Ibrahim Saadeh",
    "Nizar Al-Rashdan",
    "Noor Al-Rawabdeh",
    "Mohannad Abu Taha",
    "Team-Foto",
    "Amer Jamous",
    "Musa Al-Taamari",
    "Yazan Al-Naimat",
    "Mahmoud Al-Mardi",
    "Ali Olwan",
    "Mohammad Abu Zrayq",
    "Ibrahim Sabra",
  ],
  POR: [
    "Team-Logo",
    "Diogo Costa",
    "Jose Sa",
    "Ruben Dias",
    "João Cancelo",
    "Diogo Dalot",
    "Nuno Mendes",
    "Gonçalo Inácio",
    "Bernardo Silva",
    "Bruno Fernandes",
    "Ruben Neves",
    "Vitinha",
    "Team-Foto",
    "João Neves",
    "Cristiano Ronaldo",
    "Francisco Trincao",
    "João Felix",
    "Gonçalo Ramos",
    "Pedro Neto",
    "Rafael Leão",
  ],
  COD: [
    "Team-Logo",
    "Lionel Mpasi",
    "Aaron Wan-Bissaka",
    "Axel Tuanzebe",
    "Arthur Masuaku",
    "Chancel Mbemba",
    "Joris Kayembe",
    "Charles Pickel",
    "Ngal'ayel Mukau",
    "Edo Kayembe",
    "Samuel Moutoussamy",
    "Noah Sadiki",
    "Team-Foto",
    "Théo Bongonda",
    "Meschak Elia",
    "Yoane Wissa",
    "Brian Cipenga",
    "Fiston Mayele",
    "Cédric Bakambu",
    "Nathanaël Mbuku",
  ],
  UZB: [
    "Team-Logo",
    "Utkir Yusupov",
    "Farrukh Savfiev",
    "Sherzod Nasrullaev",
    "Umar Eshmurodov",
    "Husniddin Aliqulov",
    "Rustamjon Ashurmatov",
    "Khojiakbar Alijonov",
    "Abdukodir Khusanov",
    "Odiljon Hamrobekov",
    "Otabek Shukurov",
    "Jamshid Iskanderov",
    "Team-Foto",
    "Azizbek Turgunboev",
    "Khojimat Erkinov",
    "Eldor Shomurodov",
    "Oston Urunov",
    "Jaloliddin Masharipov",
    "Igor Sergeev",
    "Abbosbek Fayzullaev",
  ],
  COL: [
    "Team-Logo",
    "Camilo Vargas",
    "David Ospina",
    "Dávinson Sánchez",
    "Yerry Mina",
    "Daniel Munoz",
    "Johan Mojica",
    "Jhon Lucumí",
    "Santiago Arias",
    "Jefferson Lerma",
    "Kevin Castaño",
    "Richard Rios",
    "Team-Foto",
    "James Rodriguez",
    "Juan Fernando Quintero",
    "Jorge Carrascal",
    "Jon Arias",
    "Jhon Cordova",
    "Luis Suarez",
    "Luis Diaz",
  ],
  ENG: [
    "Team-Logo",
    "Jordan Pickford",
    "John Stones",
    "Marc Guéhi",
    "Ezri Konsa",
    "Trent Alexander-Arnold",
    "Reece James",
    "Dan Burn",
    "Jordan Henderson",
    "Declan Rice",
    "Jude Bellingham",
    "Cole Palmer",
    "Team-Foto",
    "Morgan Rogers",
    "Anthony Gordon",
    "Phil Foden",
    "Bukayo Saka",
    "Harry Kane",
    "Marcus Rashford",
    "Ollie Watkins",
  ],
  CRO: [
    "Team-Logo",
    "Dominik Livaković",
    "Duje Caleta-Car",
    "Josko Gvardiol",
    "Josip Stanišić",
    "Luka Vušković",
    "Josip Sutalo",
    "Kristijan Jakic",
    "Luka Modrić",
    "Mateo Kovacic",
    "Martin Baturina",
    "Lovro Majer",
    "Team-Foto",
    "Mario Pasalic",
    "Petar Sucic",
    "Ivan Perišić",
    "Marco Pasalic",
    "Ante Budimir",
    "Andrej Kramarić",
    "Franjo Ivanovic",
  ],
  GHA: [
    "Team-Logo",
    "Lawrence Ati Zigi",
    "Tariq Lamptey",
    "Mohammed Salisu",
    "Alidu Seidu",
    "Alexander Djiku",
    "Gideon Mensah",
    "Caleb Yirenkyi",
    "Abdul Issahaku Fatawu",
    "Thomas Partey",
    "Salis Abdul Samed",
    "Kamaldeen Sulemana",
    "Team-Foto",
    "Mohammed Kudus",
    "Inaki Williams",
    "Jordan Ayew",
    "Andrew Ayew",
    "Joseph Paintsil",
    "Osman Bukari",
    "Antoine Semenyo",
  ],
  PAN: [
    "Team-Logo",
    "Orlando Mosquera",
    "Luis Mejia",
    "Fidel Escobar",
    "Andres Andrade",
    "Michael Amir Murillo",
    "Eric Davis",
    "Jose Cordoba",
    "Cesar Blackman",
    "Cristian Martinez",
    "Aníbal Godoy",
    "Adalberto Carrasquilla",
    "Team-Foto",
    "Édgar Bárcenas",
    "Carlos Harvey",
    "Ismael Díaz",
    "Jose Fajardo",
    "Cecilio Waterman",
    "Jose Luiz Rodriguez",
    "Alberto Quintero",
  ],
};


// Returns the full name of a sticker based on its code
export function getStickerName(code: string): string {
  const match = code.trim().toUpperCase().match(/^([A-Z]{3})([0-9]+)$/);
  if (!match) return "Unbekannter Sticker";
  const country = match[1];
  const num = parseInt(match[2], 10);
  const idx = num - 1; // 0-indexed

  const names = PLAYER_NAMES[country];
  if (names && names[idx]) {
    return names[idx];
  }

  // Fallback
  if (country === "FWC") {
    if (num === 1) return "FIFA World Cup Pokal";
    return `Spezial #${num}`;
  }
  if (num === 1) return "Wappen / Logo";
  return `Spieler #${num}`;
}

/**
 * Returns the URL to the sticker image.
 * Files are stored as "#GER001.webp", "#ARG010.webp", etc.
 * The code format in the app is "GER1", "ARG10", "FWC3", etc.
 */
export function getStickerImageUrl(code: string): string | null {
  const match = code.trim().toUpperCase().match(/^([A-Z]{3})([0-9]+)$/);
  if (!match) return null;
  const country = match[1];
  const num = parseInt(match[2], 10);
  const paddedNum = String(num).padStart(3, "0");
  // File is named e.g. "#GER001.webp" — the # is URL-encoded as %23
  return `/stickers/%23${country}${paddedNum}.webp`;
}

/**
 * Returns the placeholder image URL.
 */
export function getStickerPlaceholderUrl(): string {
  return `/stickers/%23PL000.webp`;
}

export const COUNTRY_ISO_MAP: Record<string, string> = {
  GER: "de", USA: "us", MEX: "mx", CAN: "ca", ARG: "ar", BRA: "br",
  ECU: "ec", FRA: "fr", ENG: "gb-eng", ESP: "es", POR: "pt", BIH: "ba",
  CRO: "hr", NED: "nl", BEL: "be", SUI: "ch", AUT: "at", TUR: "tr",
  CZE: "cz", NOR: "no", SCO: "gb-sct", NZL: "nz", SWE: "se", COL: "co",
  URU: "uy", MAR: "ma", TUN: "tn", EGY: "eg", ALG: "dz", JOR: "jo",
  GHA: "gh", SEN: "sn", CUW: "cw", RSA: "za", CPV: "cv", COD: "cd",
  CIV: "ci", JPN: "jp", KOR: "kr", AUS: "au", IRN: "ir", KSA: "sa",
  IRQ: "iq", UZB: "uz", QAT: "qa", PAN: "pa", PAR: "py", HAI: "ht",
};

export function getCountryFlagUrl(countryCode: string): string {
  const code = countryCode.trim().toUpperCase();
  if (code === "FWC") {
    return "/2026-FIFA-World-Cup-logo.png";
  }
  const iso = COUNTRY_ISO_MAP[code];
  if (iso) return `https://flagcdn.com/w80/${iso}.png`;
  return "https://flagcdn.com/w80/un.png";
}
